;<?php die();?>

[path]
confMsgFR = "../assets/config/confMsgFR.ini.php"
directoryimage= "./"
functions = "../includes/functions/functions.php"
functions.html = "../includes/functions/functions.html.php"
functionsSQL = "../includes/functions/functions.sql.php"
logout = "logout.php"
dashboard = "../includes/elements/dashboard.php"
navigationBar = "../includes/elements/navigationBar.php"
site = "../includes/elements/site.php"
login = "../includes/elements/login.php"
products = "../includes/elements/products/products.php"
products.all = "../includes/elements/products/products.all.php"
products.add = "../includes/elements/products/products.add.php"
settings = "../includes/elements/settings.php"
users = "../includes/elements/users/users.php"
users.all = "../includes/elements/users/users.all.php"
users.add = "../includes/elements/users/users.add.php"
users.me = "../includes/elements/users/users.me.php"
creations = "../includes/elements/creations/creations.php"
creations.all = "../includes/elements/creations/creations.all.php"
creations.add = "../includes/elements/creations/creations.add.php"
creations.edit = "../includes/elements/creations/creations.edit.php"
news = "../includes/elements/news/news.php"
news.all = "../includes/elements/news/news.all.php"
news.add = "../includes/elements/news/news.add.php"
news.edit = "../includes/elements/news/news.edit.php"

[cookies]
usernameLife = "31"
sessionLife = "7"
langLife = "31"
browserChoice = "31"